In [19]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.metrics import confusion_matrix
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dropout, Flatten, Dense, BatchNormalization

In [20]:
train_data = pd.read_csv('data/train.csv')
validate_data = pd.read_csv('data/validate.csv')
test_data = pd.read_csv('data/test.csv')

In [21]:
X_train = train_data.iloc[:, 1:].values.reshape(-1, 28, 28, 1) / 255
y_train = pd.get_dummies(train_data.iloc[:, 0]).values
X_val = validate_data.iloc[:, 1:].values.reshape(-1, 28, 28, 1) / 255
y_val = pd.get_dummies(validate_data.iloc[:, 0]).values
X_test = test_data.iloc[:, 1:].values.reshape(-1, 28, 28, 1) / 255
y_test = pd.get_dummies(test_data.iloc[:, 0]).values

In [22]:
model = tf.keras.models.Sequential()

In [23]:
model.add(Conv2D(64, kernel_size=(5, 5), activation='relu', input_shape=(28, 28, 1)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

In [24]:
optimizer = tf.keras.optimizers.Adadelta(learning_rate=0.01)  # learning rate #optimizer

model.compile(loss=tf.keras.losses.categorical_crossentropy, # loss function
              optimizer=optimizer,
              metrics=['accuracy'])

In [25]:
model.fit(X_train, y_train,
          batch_size=128, #batch size
          epochs=10, #num of epochs
          verbose=1,
          validation_data=(X_val, y_val))

Epoch 1/10
438/438 [==============================] - 24s 55ms/step - loss: 0.6187 - accuracy: 0.7960 - val_loss: 0.3924 - val_accuracy: 0.8500
Epoch 2/10
438/438 [==============================] - 23s 52ms/step - loss: 0.4407 - accuracy: 0.8435 - val_loss: 0.3562 - val_accuracy: 0.8697
Epoch 3/10
438/438 [==============================] - 24s 54ms/step - loss: 0.4254 - accuracy: 0.8513 - val_loss: 0.3532 - val_accuracy: 0.8737
Epoch 4/10
438/438 [==============================] - 25s 57ms/step - loss: 0.4185 - accuracy: 0.8536 - val_loss: 0.3202 - val_accuracy: 0.8856
Epoch 5/10
438/438 [==============================] - 25s 56ms/step - loss: 0.4178 - accuracy: 0.8568 - val_loss: 0.3839 - val_accuracy: 0.8604
Epoch 6/10
438/438 [==============================] - 29s 67ms/step - loss: 0.4149 - accuracy: 0.8571 - val_loss: 0.3247 - val_accuracy: 0.8803
Epoch 7/10
438/438 [==============================] - 29s 67ms/step - loss: 0.4172 - accuracy: 0.8596 - val_loss: 0.3143 - val_accuracy:

In [26]:
score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.4023425877094269
Test accuracy: 0.8642857074737549


In [27]:
y_pred = model.predict(X_test)
confusion_matrix = confusion_matrix(y_test.argmax(axis=1), y_pred.argmax(axis=1))
print('Confusion Matrix:')
print(confusion_matrix)

219/219 [==============================] - 1s 4ms/step
Confusion Matrix:
[[587   3  16  15   3   0  74   1   3   0]
 [  1 679   3   9   1   0   2   0   0   0]
 [  3   1 567  10 100   0  24   0   0   0]
 [ 13   6   2 665  20   0  10   0   1   0]
 [  0   2  92  32 556   0  12   0   0   0]
 [  0   0   0   0   0 655   0  18   0   7]
 [106   0 130  23 102   0 333   0   2   0]
 [  0   0   0   0   0   7   0 665   0  12]
 [  1   0   9   3  12   4  10   3 651   0]
 [  0   0   1   1   1   1   1  37   0 692]]
