In [10]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.metrics import confusion_matrix
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dropout, Flatten, Dense

In [11]:
train_data = pd.read_csv('data/train.csv')
validate_data = pd.read_csv('data/validate.csv')
test_data = pd.read_csv('data/test.csv')

In [12]:
X_train = train_data.iloc[:, 1:].values.reshape(-1, 28, 28, 1) / 255
y_train = pd.get_dummies(train_data.iloc[:, 0]).values
X_val = validate_data.iloc[:, 1:].values.reshape(-1, 28, 28, 1) / 255
y_val = pd.get_dummies(validate_data.iloc[:, 0]).values
X_test = test_data.iloc[:, 1:].values.reshape(-1, 28, 28, 1) / 255
y_test = pd.get_dummies(test_data.iloc[:, 0]).values

In [13]:
model = tf.keras.models.Sequential()

In [14]:
model.add(Conv2D(32, kernel_size=(5, 5), activation='relu', input_shape=(28, 28, 1)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

In [15]:
optimizer = tf.keras.optimizers.Adadelta(learning_rate=0.01)  # learning rate #optimizer

model.compile(loss=tf.keras.losses.categorical_crossentropy, # loss function
              optimizer=optimizer,
              metrics=['accuracy'])

In [16]:
model.fit(X_train, y_train,
          batch_size=128, #batch size
          epochs=10, #num of epochs
          verbose=1,
          validation_data=(X_val, y_val))

Epoch 1/10


438/438 [==============================] - 16s 31ms/step - loss: 2.2008 - accuracy: 0.2268 - val_loss: 1.9703 - val_accuracy: 0.4984
Epoch 2/10
438/438 [==============================] - 14s 31ms/step - loss: 1.7164 - accuracy: 0.4204 - val_loss: 1.2644 - val_accuracy: 0.6511
Epoch 3/10
438/438 [==============================] - 16s 36ms/step - loss: 1.3136 - accuracy: 0.5282 - val_loss: 1.0020 - val_accuracy: 0.6944
Epoch 4/10
438/438 [==============================] - 13s 29ms/step - loss: 1.1368 - accuracy: 0.5918 - val_loss: 0.8835 - val_accuracy: 0.7207
Epoch 5/10
438/438 [==============================] - 14s 32ms/step - loss: 1.0332 - accuracy: 0.6329 - val_loss: 0.8144 - val_accuracy: 0.7317
Epoch 6/10
438/438 [==============================] - 14s 31ms/step - loss: 0.9607 - accuracy: 0.6582 - val_loss: 0.7664 - val_accuracy: 0.7357
Epoch 7/10
438/438 [==============================] - 16s 36ms/step - loss: 0.9124 - accuracy: 0.6774 - val_loss: 0.7322 - val_accurac

In [17]:
score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.6668069958686829
Test accuracy: 0.7571428418159485


In [18]:
y_pred = model.predict(X_test)
confusion_matrix = confusion_matrix(y_test.argmax(axis=1), y_pred.argmax(axis=1))
print('Confusion Matrix:')
print(confusion_matrix)

219/219 [==============================] - 1s 3ms/step
Confusion Matrix:
[[547   8  15  76   9   4  34   1   8   0]
 [  0 648   5  28   3   1   9   0   1   0]
 [  8   0 439   3 204   5  37   1   8   0]
 [ 32  30   3 575  48   2  26   0   1   0]
 [  0   4 101  32 518   2  35   0   2   0]
 [  0   1   0   1   0 593   0  65   3  17]
 [149   6 199  37 180   9 106   0  10   0]
 [  0   0   0   0   0  50   0 584   2  48]
 [  7   6  10  12   6  21  17   1 611   2]
 [  0   0   0   1   1  10   0  43   0 679]]
