In [22]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.metrics import confusion_matrix
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dropout, Flatten, Dense

In [23]:
train_data = pd.read_csv('data/train.csv')
validate_data = pd.read_csv('data/validate.csv')
test_data = pd.read_csv('data/test.csv')

In [24]:
X_train = train_data.iloc[:, 1:].values.reshape(-1, 28, 28, 1) / 255
y_train = pd.get_dummies(train_data.iloc[:, 0]).values
X_val = validate_data.iloc[:, 1:].values.reshape(-1, 28, 28, 1) / 255
y_val = pd.get_dummies(validate_data.iloc[:, 0]).values
X_test = test_data.iloc[:, 1:].values.reshape(-1, 28, 28, 1) / 255
y_test = pd.get_dummies(test_data.iloc[:, 0]).values

In [25]:
model = tf.keras.models.Sequential()

In [26]:
model.add(Conv2D(32, kernel_size=(5, 5), activation='relu', input_shape=(28, 28, 1))) #num of kernels #kernel size 
model.add(MaxPooling2D(pool_size=(2, 2))) #filter size
model.add(Dropout(0.25)) #dropout probability
model.add(Flatten())
# model.add(Dense(128, activation='relu')) #activation function
# model.add(Dropout(0.5)) #dropout probability
model.add(Dense(10, activation='softmax')) #activation function

In [27]:
optimizer = tf.keras.optimizers.Adadelta(learning_rate=0.01)  # learning rate #optimizer

model.compile(loss=tf.keras.losses.categorical_crossentropy, # loss function
              optimizer=optimizer,
              metrics=['accuracy'])

In [28]:
model.fit(X_train, y_train,
          batch_size=128, #batch size
          epochs=10, #num of epochs
          verbose=1,
          validation_data=(X_val, y_val))

Epoch 1/10
438/438 [==============================] - 12s 25ms/step - loss: 2.0277 - accuracy: 0.4011 - val_loss: 1.6271 - val_accuracy: 0.5906
Epoch 2/10
438/438 [==============================] - 8s 19ms/step - loss: 1.2861 - accuracy: 0.6102 - val_loss: 1.0436 - val_accuracy: 0.6553
Epoch 3/10
438/438 [==============================] - 10s 22ms/step - loss: 0.9600 - accuracy: 0.6721 - val_loss: 0.8787 - val_accuracy: 0.7010
Epoch 4/10
438/438 [==============================] - 8s 18ms/step - loss: 0.8492 - accuracy: 0.7063 - val_loss: 0.8003 - val_accuracy: 0.7249
Epoch 5/10
438/438 [==============================] - 10s 23ms/step - loss: 0.7871 - accuracy: 0.7267 - val_loss: 0.7500 - val_accuracy: 0.7461
Epoch 6/10
438/438 [==============================] - 7s 17ms/step - loss: 0.7467 - accuracy: 0.7383 - val_loss: 0.7141 - val_accuracy: 0.7543
Epoch 7/10
438/438 [==============================] - 7s 17ms/step - loss: 0.7160 - accuracy: 0.7481 - val_loss: 0.6874 - val_accuracy: 0.7

In [29]:
score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.6307464241981506
Test accuracy: 0.7801428437232971


In [30]:
y_pred = model.predict(X_test)
confusion_matrix = confusion_matrix(y_test.argmax(axis=1), y_pred.argmax(axis=1))
print('Confusion Matrix:')
print(confusion_matrix)

219/219 [==============================] - 0s 2ms/step
Confusion Matrix:
[[544   7   8  83   5   0  44   1  10   0]
 [  0 646   9  24   7   0   8   0   1   0]
 [  4   2 425   1 160   0 104   0   9   0]
 [ 20  12   2 630  14   0  35   0   4   0]
 [  0   3 113  38 479   1  56   0   4   0]
 [  0   0   0   2   0 594   0  59   0  25]
 [143   3 130  51 116   1 235   0  17   0]
 [  0   0   0   0   0  35   0 602   3  44]
 [  2   0  11  20   3   5  21   2 626   3]
 [  0   0   0   0   1   5   0  47   1 680]]
